/**
 * Runs a lightweight end-to-end probe for long-output session id capture.
 * Important note: it uses a temporary fake Codex binary so no external agent is required.
 */

import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";

/** A stable fake session id emitted before the long filler output. */
const PROBE_SESSION_ID = "11111111-2222-3333-4444-555555555555";

/** Creates the temporary fake Codex executable used by the probe. */
async function createMockCodexBinary(filePath: string): Promise<void> {
  const source = `#!/usr/bin/env node
const fs = require("node:fs");

const args = process.argv.slice(2);
const summaryIndex = args.indexOf("-o");
const summaryPath = summaryIndex >= 0 ? args[summaryIndex + 1] : null;
const prompt = args.at(-1) ?? "";
const reportMatch = prompt.match(/Write a JSON object to: (.+)/);
const reportPath = reportMatch ? reportMatch[1].trim() : null;

process.stdout.write("booting mock codex\\n");
process.stdout.write("session id: ${PROBE_SESSION_ID}\\n");
process.stdout.write("X".repeat(350 * 1024));
process.stdout.write("\\nmock codex finished\\n");

if (summaryPath) {
  fs.writeFileSync(summaryPath, "Mock probe summary\\n", "utf8");
}

if (reportPath) {
  fs.writeFileSync(
    reportPath,
    JSON.stringify(
      {
        taskSummary: "Mock probe completed.",
        modifiedFiles: [],
        projectModifiedFiles: [],
        artifactFiles: [],
        validation: ["probe mock agent completed"],
        validationSummary: "probe mock agent ✅",
        notes: "Generated by session-id probe.",
        commitId: null,
      },
      null,
      2,
    ) + "\\n",
    "utf8",
  );
}
`;

  await writeFile(filePath, source, { encoding: "utf8", mode: 0o755 });
}

/** Runs the wrapper against the fake agent and verifies session id recovery. */
async function main(): Promise<void> {
  const workspace = path.resolve(
    __dirname,
    "..",
    `.probe-workspace-${process.pid}-${Date.now()}`,
  );
  const fakeRepo = path.join(workspace, "repo");
  const outputRoot = path.join(workspace, "runs");
  const mockCodexPath = path.join(workspace, "mock-codex.js");
  const cliPath = path.resolve(__dirname, "cli.js");
  const runId = "probe-long-output-session-id";

  try {
    await mkdir(fakeRepo, { recursive: true });
    await createMockCodexBinary(mockCodexPath);

    const result = spawnSync(
      process.execPath,
      [
        cliPath,
        "run",
        "--agent",
        "codex",
        "--cwd",
        fakeRepo,
        "--task",
        "Probe long session id capture.",
        "--output-root",
        outputRoot,
        "--run-id",
        runId,
        "--started-at",
        new Date().toISOString(),
      ],
      {
        encoding: "utf8",
        env: {
          ...process.env,
          CODEX_API_KEY: "probe-key",
          CODING_AGENT_WRAPPER_CODEX_BIN: mockCodexPath,
        },
      },
    );

    assert.equal(
      result.status,
      0,
      result.stderr || result.stdout || "probe run failed",
    );

    const resultPath = path.join(outputRoot, runId, "result.json");
    const logPath = path.join(outputRoot, runId, "run.log");
    const sessionIndexPath = path.join(outputRoot, "session-index.json");
    const runResult = JSON.parse(await readFile(resultPath, "utf8")) as {
      sessionId?: string | null;
    };
    const sessionIndex = JSON.parse(
      await readFile(sessionIndexPath, "utf8"),
    ) as {
      entries?: Record<string, { sessionId?: string }>;
    };
    const logContent = await readFile(logPath, "utf8");
    const sessionKey = `codex::${fakeRepo}`;

    assert.equal(
      runResult.sessionId,
      PROBE_SESSION_ID,
      "result.json should keep the early session id",
    );
    assert.equal(
      sessionIndex.entries?.[sessionKey]?.sessionId,
      PROBE_SESSION_ID,
      "session-index.json should store the recovered session id",
    );
    assert.ok(
      logContent.length > 256 * 1024,
      "run.log should be large enough to exceed the in-memory capture limit",
    );

    process.stdout.write(
      `${[
        `probe run: ${runId}`,
        `log size: ${logContent.length} bytes`,
        `session id captured: ${runResult.sessionId}`,
        "long-output session id recovery: PASS",
      ].join("\n")}\n`,
    );
  } finally {
    await rm(workspace, { recursive: true, force: true });
  }
}

main().catch((error: unknown) => {
  const message = error instanceof Error ? error.message : String(error);
  process.stderr.write(`${message}\n`);
  process.exitCode = 1;
});
