/**
 * Verifies same-project single-flight rejection and stale lock recovery.
 * Important note: it uses a temporary mock Codex binary, so no real agent or
 * network access is required during the probe.
 */

import assert from "node:assert/strict";
import { spawn, spawnSync } from "node:child_process";
import { mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";

import { getActiveRunLockPaths } from "./single-flight";
import type { RunResult } from "./types";

/** Creates the fake Codex executable used by the probe scenarios. */
async function createMockCodexBinary(filePath: string): Promise<void> {
  const source = `#!/usr/bin/env node
const fs = require("node:fs");

const args = process.argv.slice(2);
const summaryIndex = args.indexOf("-o");
const summaryPath = summaryIndex >= 0 ? args[summaryIndex + 1] : null;
const prompt = args.at(-1) ?? "";
const reportMatch = prompt.match(/Write a JSON object to: (.+)/);
const reportPath = reportMatch ? reportMatch[1].trim() : null;
const mode = process.env.MOCK_CODEX_MODE ?? "fast";
const holdMs = Number(process.env.MOCK_CODEX_HOLD_MS ?? "0");

function finish() {
  if (summaryPath) {
    fs.writeFileSync(summaryPath, "Mock single-flight probe summary\\n", "utf8");
  }

  if (reportPath) {
    fs.writeFileSync(
      reportPath,
      [
        JSON.stringify(
          {
            taskSummary: "Mock single-flight probe completed.",
            modifiedFiles: [],
            projectModifiedFiles: [],
            artifactFiles: [],
            validation: ["mock codex completed"],
            validationSummary: "mock codex ✅",
            notes: "Generated by single-flight probe.",
            commitId: null,
          },
          null,
          2,
        ),
        "",
      ].join("\\n"),
      "utf8",
    );
  }

  process.exit(0);
}

process.stdout.write("mock codex started\\n");
if (mode === "hold") {
  setTimeout(finish, holdMs);
} else {
  finish();
}
`;

  await writeFile(filePath, source, { encoding: "utf8", mode: 0o755 });
}

/** Runs the probe scenarios and prints a short PASS summary. */
async function main(): Promise<void> {
  const repoRoot = path.resolve(__dirname, "..");
  await cleanupProbeWorkspaces(repoRoot);

  const workspace = path.resolve(
    repoRoot,
    `.probe-workspace-${process.pid}-${Date.now()}`,
  );
  const fakeRepo = path.join(workspace, "repo");
  const outputRoot = path.join(workspace, "runs");
  const mockCodexPath = path.join(workspace, "mock-codex.js");
  const cliPath = path.resolve(__dirname, "cli.js");

  try {
    await mkdir(fakeRepo, { recursive: true });
    await createMockCodexBinary(mockCodexPath);

    await assertActiveRunIsRejected(
      cliPath,
      fakeRepo,
      outputRoot,
      mockCodexPath,
    );
    await assertStaleLockIsRecovered(
      cliPath,
      fakeRepo,
      outputRoot,
      mockCodexPath,
    );

    process.stderr.write("single-flight active rejection: PASS\n");
    process.stderr.write("single-flight stale recovery: PASS\n");
  } finally {
    await rm(workspace, { recursive: true, force: true });
    await cleanupProbeWorkspaces(repoRoot);
  }
}

/** Verifies that a second same-project run is rejected while the first is active. */
async function assertActiveRunIsRejected(
  cliPath: string,
  fakeRepo: string,
  outputRoot: string,
  mockCodexPath: string,
): Promise<void> {
  const activeRunId = "probe-active-run";
  const sharedEnv = buildProbeEnv(mockCodexPath);
  const firstRun = spawn(
    process.execPath,
    [
      cliPath,
      "run",
      "--agent",
      "codex",
      "--cwd",
      fakeRepo,
      "--task",
      "Hold the first single-flight probe run.",
      "--output-root",
      outputRoot,
      "--run-id",
      activeRunId,
    ],
    {
      env: {
        ...sharedEnv,
        MOCK_CODEX_MODE: "hold",
        MOCK_CODEX_HOLD_MS: "2500",
      },
      stdio: "ignore",
    },
  );

  try {
    await waitForActiveLock(outputRoot);

    const secondRun = spawnSync(
      process.execPath,
      [
        cliPath,
        "run",
        "--agent",
        "claude",
        "--cwd",
        fakeRepo,
        "--task",
        "This run should be rejected by single-flight.",
        "--output-root",
        outputRoot,
        "--run-id",
        "probe-rejected-run",
      ],
      {
        encoding: "utf8",
        env: {
          ...sharedEnv,
          MOCK_CODEX_MODE: "fast",
        },
      },
    );

    assert.notEqual(secondRun.status, 0, "second run should be rejected");
    assert.match(secondRun.stderr, /同一项目已有活跃 run/);
    assert.match(secondRun.stderr, new RegExp(activeRunId));
    assert.match(secondRun.stderr, /Agent: codex/);
    assert.match(secondRun.stderr, new RegExp(escapeRegExp(fakeRepo)));
  } finally {
    await waitForExit(firstRun);
  }
}

/** Verifies that a stale lock is recovered automatically before the next run. */
async function assertStaleLockIsRecovered(
  cliPath: string,
  fakeRepo: string,
  outputRoot: string,
  mockCodexPath: string,
): Promise<void> {
  const staleRunId = "probe-stale-run";
  const newRunId = "probe-recovered-run";
  const stalePaths = getActiveRunLockPaths(outputRoot, "codex", fakeRepo);
  const staleResultDir = path.join(outputRoot, staleRunId);
  const staleResultPath = path.join(staleResultDir, "result.json");

  await rm(stalePaths.lockDir, { recursive: true, force: true });
  await mkdir(stalePaths.lockDir, { recursive: true });
  await mkdir(staleResultDir, { recursive: true });
  await writeFile(
    stalePaths.claimFilePath,
    `${JSON.stringify(
      {
        claimId: "stale-claim",
        agent: "codex",
        cwd: fakeRepo,
        runId: staleRunId,
        startedAt: new Date().toISOString(),
        claimedAt: new Date().toISOString(),
        pid: 999999,
        pidStartTimeTicks: "0",
        resultPath: staleResultPath,
      },
      null,
      2,
    )}\n`,
    "utf8",
  );
  await writeFile(
    staleResultPath,
    `${JSON.stringify(buildRunningResult(staleRunId, fakeRepo, staleResultPath), null, 2)}\n`,
    "utf8",
  );

  const recoveredRun = spawnSync(
    process.execPath,
    [
      cliPath,
      "run",
      "--agent",
      "codex",
      "--cwd",
      fakeRepo,
      "--task",
      "Recover the stale active lock.",
      "--output-root",
      outputRoot,
      "--run-id",
      newRunId,
    ],
    {
      encoding: "utf8",
      env: {
        ...buildProbeEnv(mockCodexPath),
        MOCK_CODEX_MODE: "fast",
      },
    },
  );

  assert.equal(
    recoveredRun.status,
    0,
    recoveredRun.stderr || recoveredRun.stdout,
  );

  const recoveredResultPath = path.join(outputRoot, newRunId, "result.json");
  const recoveredResult = JSON.parse(
    await readFile(recoveredResultPath, "utf8"),
  ) as RunResult;
  assert.equal(
    recoveredResult.status,
    "success",
    "recovered run should succeed",
  );

  const activeEntries = await readActiveRunEntries(outputRoot);
  assert.equal(
    activeEntries.length,
    0,
    "stale lock should be released after recovered run",
  );
}

/** Builds a minimal running result.json payload for the stale-lock scenario. */
function buildRunningResult(
  runId: string,
  cwd: string,
  resultPath: string,
): RunResult {
  const runDir = path.dirname(resultPath);
  return {
    runId,
    agent: "codex",
    cwd,
    taskSummary: "stale lock placeholder",
    startedAt: new Date().toISOString(),
    finishedAt: null,
    durationMinutes: null,
    exitCode: null,
    status: "running",
    logPath: path.join(runDir, "run.log"),
    resultPath,
    summaryPath: path.join(runDir, "agent-summary.txt"),
    reportPath: path.join(runDir, "agent-report.json"),
    summary: "running",
    agentSummary: "running",
    validation: [],
    validationSummary: null,
    notes: null,
    commitId: null,
    sessionId: null,
    resumedFromSessionId: null,
    pid: 999999,
    claimedAt: new Date().toISOString(),
    terminationReason: null,
    modifiedFiles: [],
    projectModifiedFiles: [],
    artifactFiles: [],
  };
}

/** Builds a quiet probe environment that avoids real notification delivery. */
function buildProbeEnv(mockCodexPath: string): NodeJS.ProcessEnv {
  return {
    ...process.env,
    CODEX_API_KEY: "probe-key",
    CODING_AGENT_WRAPPER_CODEX_BIN: mockCodexPath,
    OPENCLAW_BIN: "/nonexistent-openclaw",
    NOTIFY_TARGET: "",
    NOTIFY_SESSION_KEY: "",
  };
}

/** Waits until the active-runs directory contains at least one claimed lock. */
async function waitForActiveLock(outputRoot: string): Promise<void> {
  const timeoutAt = Date.now() + 4000;
  while (Date.now() < timeoutAt) {
    const entries = await readActiveRunEntries(outputRoot);
    if (entries.length > 0) {
      return;
    }
    await sleep(50);
  }

  throw new Error("Timed out waiting for the active run lock.");
}

/** Lists the active lock directory entries under the probe output root. */
async function readActiveRunEntries(outputRoot: string): Promise<string[]> {
  try {
    return await readdir(path.join(outputRoot, "active-runs"));
  } catch {
    return [];
  }
}

/** Removes stale probe workspaces so repository lint does not pick them up later. */
async function cleanupProbeWorkspaces(repoRoot: string): Promise<void> {
  const entries = await readdir(repoRoot, { withFileTypes: true });
  await Promise.all(
    entries
      .filter(
        (entry) =>
          entry.isDirectory() && entry.name.startsWith(".probe-workspace-"),
      )
      .map((entry) =>
        rm(path.join(repoRoot, entry.name), { recursive: true, force: true }),
      ),
  );
}

/** Waits for one spawned wrapper process to exit cleanly. */
async function waitForExit(child: ReturnType<typeof spawn>): Promise<void> {
  await new Promise<void>((resolve, reject) => {
    child.on("exit", () => resolve());
    child.on("error", (error) => reject(error));
  });
}

/** Sleeps for a short amount of time while polling probe state. */
async function sleep(durationMs: number): Promise<void> {
  await new Promise<void>((resolve) => {
    setTimeout(resolve, durationMs);
  });
}

/** Escapes user paths before embedding them into regular expressions. */
function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

main().catch((error: unknown) => {
  const message = error instanceof Error ? error.message : String(error);
  process.stderr.write(`${message}\n`);
  process.exitCode = 1;
});
